# Generated by Django 5.2.8 on 2025-11-28 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('tenth_marks', models.FloatField(blank=True, null=True)),
                ('twelfth_marks', models.FloatField(blank=True, null=True)),
                ('twelfth_stream', models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('other', 'Other')], max_length=20, null=True)),
                ('has_diploma', models.BooleanField(default=False)),
                ('diploma_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('diploma_marks', models.FloatField(blank=True, null=True)),
                ('has_degree', models.BooleanField(default=False)),
                ('degree_name', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_cgpa', models.FloatField(blank=True, null=True)),
                ('backlogs', models.IntegerField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('soft_skills', models.TextField(blank=True, null=True)),
                ('languages_known', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('favorite_subjects', models.TextField(blank=True, null=True)),
                ('personality_traits', models.TextField(blank=True, null=True)),
                ('short_term_goal', models.TextField(blank=True, null=True)),
                ('long_term_goal', models.TextField(blank=True, null=True)),
                ('dream_job', models.CharField(blank=True, max_length=200, null=True)),
                ('study_preference', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=20, null=True)),
                ('career_path', models.CharField(blank=True, choices=[('job', 'Job'), ('business', 'Business'), ('freelancing', 'Freelancing'), ('higher_study', 'Higher Study'), ('government', 'Government Exams')], max_length=20, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
