# Generated by Django 5.2.8 on 2025-11-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprogress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
